CREATE TABLE events (
            id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
            timestamp TIMESTAMP NOT NULL,
            eventName VARCHAR(30) NOT NULL,
            sourceGUID VARBINARY DEFAULT NULL,
            sourceName VARCHAR(50) DEFAULT NULL,
            sourceFlags VARBINARY DEFAULT NULL,
            targetGUID VARBINARY DEFAULT NULL,
            targetName VARCHAR(50) DEFAULT NULL,
            targetFlags VARBINARY DEFAULT NULL,
            spellID MEDIUMINT DEFAULT NULL,
            environmentalType VARCHAR(8) DEFAULT NULL,
            spellName VARCHAR(30) DEFAULT NULL,
            spellSchool VARBINARY DEFAULT NULL,
            amount MEDIUMINT UNSIGNED DEFAULT NULL,
            overkill MEDIUMINT UNSIGNED DEFAULT NULL,
            school TINYINT DEFAULT NULL,
            resisted MEDIUMINT UNSIGNED DEFAULT NULL,
            blocked MEDIUMINT UNSIGNED DEFAULT NULL,
            absorbed MEDIUMINT UNSIGNED DEFAULT NULL,
            critical BOOLEAN DEFAULT NULL,
            glancing BOOLEAN DEFAULT NULL,
            crushing BOOLEAN DEFAULT NULL,
            missType VARCHAR(7) DEFAULT NULL,
            overhealing MEDIUMINT UNSIGNED DEFAULT NULL,
            overEnergize MEDIUMINT UNSIGNED DEFAULT NULL,
            powerType TINYINT DEFAULT NULL,
            extraAmount MEDIUMINT UNSIGNED DEFAULT NULL,
            extraSpellID MEDIUMINT UNSIGNED DEFAULT NULL,
            extraSpellName VARCHAR(30) DEFAULT NULL,
            extraSchool VARBINARY DEFAULT NULL,
            auraType VARCHAR(6) DEFAULT NULL,
            itemID SMALLINT UNSIGNED DEFAULT NULL,
            itemName VARCHAR(50) DEFAULT NULL
        )