CREATE TABLE events (
            id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
            timestamp TIMESTAMP NOT NULL,
            eventName VARCHAR(30) NOT NULL,
            sourceGUID VARBINARY,
            sourceName VARCHAR(50),
            sourceFlags VARBINARY,
            targetGUID VARBINARY,
            targetName VARCHAR(50),
            targetFlags VARBINARY,
            spellID MEDIUMINT,
            environmentalType VARCHAR(8),
            spellName VARCHAR(30),
            spellSchool VARBINARY,
            amount MEDIUMINT UNSIGNED,
            overkill MEDIUMINT UNSIGNED,
            school TINYINT,
            resisted MEDIUMINT UNSIGNED,
            blocked MEDIUMINT UNSIGNED,
            absorbed MEDIUMINT UNSIGNED,
            critical BOOLEAN,
            glancing BOOLEAN,
            crushing BOOLEAN,
            missType VARCHAR(7),
            overhealing MEDIUMINT UNSIGNED,
            overEnergize MEDIUMINT UNSIGNED,
            powerType TINYINT,
            extraAmount MEDIUMINT UNSIGNED,
            extraSpellID MEDIUMINT UNSIGNED,
            extraSpellName VARCHAR(30),
            extraSchool VARBINARY,
            auraType VARCHAR(6),
            itemID SMALLINT UNSIGNED,
            itemName VARCHAR(50)
        )